
openapi: 3.0.0
info:
  title: Pack Calculator API
  version: 1.0.0
  description: Calculates the optimal pack sizes for a given item count.
servers:
  - url: http://54.91.1.171:8080
paths:
  /calculate:
    post:
      summary: Calculate optimal pack breakdown
      description: |
        This endpoint calculates the optimal pack combination.

        #### 📦 Example cURL:
        ```bash
        curl -X POST http://54.91.1.171:8080/calculate \
          -H "Content-Type: application/json" \
          -d '{"items": 251, "pack_sizes": [250, 500, 1000]}'
        ```
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                items:
                  type: integer
                  example: 251
                pack_sizes:
                  type: array
                  items:
                    type: integer
                  example: [250, 500, 1000]
      responses:
        '200':
          description: Pack result
          content:
            application/json:
              schema:
                type: object
                properties:
                  packs:
                    type: object
                    additionalProperties:
                      type: integer
                    example: { "500": 1 }
                  total_items:
                    type: integer
                    example: 500
                  total_packs:
                    type: integer
                    example: 1